### ISSUE TITLE
External IP pending

### ISSUE THREAD

**Issue by Rocknpools** [colemickens/azkube#11]
Hi guys. I'm trying to deploy a service on Kubernetes with azkube in LoadBalancer mode.
Running "kubectl get service" i got this:

NAME                  CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
monitoring-grafana    10.3.127.72   <pending>     80/TCP                       4m
monitoring-influxdb   10.3.60.140   <pending>     8083/TCP,8086/TCP            4m

it seems that the scale set created following this [http://kubernetes.io/docs/getting-started-guides/azure/](url) doesn't provide an external ip to use in LoadBalancer mode.
It is also impossible to assign a public ip to the scale set network interface using the new azure portal.
What am i doing wrong? Can someone help me with this issue?

**Comment by colemickens** [comment]
Kubernetes 1.2 and 1.3 do not support `Type=LoadBalancer` in `Service` objects in Azure, but support for it was just merged a couple of hours ago and will be available in Kubernetes 1.4.

Unfortunately, the only way that you can accomplish this is by manually configuring a load balancer and altering the VMSS model to place the NICs into the LoadBalancer backend pool. This will need to be done from the [`azure-xplat-cli`](https://github.com/Azure/azure-xplat-cli) or from [`azure-powershell`](https://github.com/Azure/azure-powershell).

I can try to find some instructions on how to do this if it would be helpful.

**Comment by Rocknpools** [comment]
@colemickens Thanks man! it would be really helpful

**Comment by Rocknpools** [comment]
Do I need to place the master's NIC into the load balancer backend pool? or the scale set NIC

Because running "azure network nic list" i got this:

data:   Name                     Location     Resource group  Provisioning state
data:    -----------------------  -----------  --------------  ------------------
data:    test-staging-nic-master   northeurope  test-staging     Succeeded
data:    test-staging-node-nic                  test-staging     Succeeded

but running "azure network nic set" i got:
- Looking up the network interface "test-staging-node-nic"
  error:   A network interface with name "mre-staging-node-nic" not found in the resource group test-staging

**Comment by colemickens** [comment]
@Rocknpools When you are using VMSS, the Compute and Network resources are at a different location from an API standpoint. So you can't interact with a single instance in a VMSS the same way you interact with normal loose instances.

I'm still trying to  get some assistance on these instructions...

**Comment by theobolo** [comment]
@Rocknpools Hello Paolo, i saw your message and for the moment as Cole told you it's not really implemented. 

By the way i got a solution for you that gonna be a little bit easier than deploy manually the LoadBalancer via CLI and attach it to the nodes.

I made a custom Azkube image that integrate some optionnal deployment stuff natively like the LoadBalancer. Since the Kubernetes 1.4 isn't released you will maybe find better to use that.

So to get the concept you will have : 
- Outside World > Azure LoadBalancer (80 / TCP linked to the nodes) > A Nginx DaemonSet on your cluster on HostPort 80 > an Ingress rule > Your POD / CONTAINERS.

You can take a look at my fork here : https://github.com/theobolo/azkube

You will need to deploy the Azkube cluster with the arg "flavor" : coreos-lb witch is integrate a LoadBalancer mapped on each node on the 80 port.

You can use my own image to do that witch is Updated with the last Azkube master branch : 
https://hub.docker.com/r/theobolo/azkube-flavor/

so to deploy a cluster in 1.3 kubernetes version on azure with a loadbalancer natively configured : 

```
docker run -it theobolo/azkube-flavor:1.0 /opt/azkube/azkube deploy \
                       --flavor="coreos-lb" \
                       --deployment-name="azkubeflavor-lb" \
                       --location="northeurope" \
                       --no-cloud-provider \
                       --subscription-id="your subscription id" \ 
                       --node-count="3" \
                       --node-size="Standard_DS1_v2" \
                       --master-size="Standard_DS2_v2"
```

With that you will have a Kubernetes cluster fully functional in 1.3 version with the Azure LoadBalancer.

Then you will have to deploy inside your k8s cluster a Nginx controller witch will be used as a 2nd level LoadBalancer (L7) : on each nodes you will have a Nginx POD witch will exposed on the 80 port of the node. 

You can find the YML of that Nginx Controller here : https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/daemonset

You can use it without any modifications, i just recommend to read a little bit about how to run it on the main page : 

https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

With the default-backend.yml and the service exposition.

Then when you have the cluster + the Nginx controller launched on each pod you will just have to create an Ingress rule : https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/ingress.yaml

This will map an URL / Domain to a Kubernetes Service by configuring Nginx controllers to LoadBalance the external requests made on the LoadBalancer Public IP to the backend PODs.

If you have any question about that contact me by mail or on slack #kubernetes @theobolo !

Have a nice day ! 
Théo

**Comment by colemickens** [comment]
There are some instructions on accomplishing this here : https://github.com/Azure/azure-cli/issues/566#issuecomment-237385728

This will help you export your VMSD configuration, modify it as needed for the load balancer and then reapply it.

If there are further questions, let's handle them as Issues on the azure-xplat-cli repository. I don't want to handle the LB configuration in azkube, for now, as it would require making assumptions about the user's workload.
